apiVersion: apps/v1
kind: Deployment
metadata:
  name: govpn-server
  namespace: govpn
  labels:
    app.kubernetes.io/name: govpn
    app.kubernetes.io/instance: govpn
    app.kubernetes.io/component: vpn-server
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: govpn
      app.kubernetes.io/instance: govpn
      app.kubernetes.io/component: vpn-server
  template:
    metadata:
      labels:
        app.kubernetes.io/name: govpn
        app.kubernetes.io/instance: govpn
        app.kubernetes.io/component: vpn-server
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9100"
        prometheus.io/path: "/metrics"
    spec:
      serviceAccountName: govpn-server
      securityContext:
        runAsNonRoot: true
        runAsUser: 65534
        runAsGroup: 65534
        fsGroup: 65534
      containers:
      - name: govpn-server
        image: govpn/server:latest
        imagePullPolicy: IfNotPresent
        ports:
        - name: vpn-udp
          containerPort: 1194
          protocol: UDP
        - name: metrics
          containerPort: 9100
          protocol: TCP
        - name: health
          containerPort: 8080
          protocol: TCP
        - name: management
          containerPort: 7505
          protocol: TCP
        env:
        - name: GOVPN_CONFIG_DIR
          value: "/etc/govpn"
        - name: GOVPN_LOG_LEVEL
          value: "info"
        - name: GOVPN_ENABLE_MONITORING
          value: "true"
        - name: GOVPN_METRICS_PORT
          value: "9100"
        - name: GOVPN_HEALTH_PORT
          value: "8080"
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: health
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: health
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        volumeMounts:
        - name: config
          mountPath: /etc/govpn
          readOnly: true
        - name: certs
          mountPath: /etc/govpn/certs
          readOnly: true
        - name: logs
          mountPath: /var/log/govpn
        - name: tmp
          mountPath: /tmp
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities:
            add:
            - NET_ADMIN
            - NET_RAW
            drop:
            - ALL
      - name: log-forwarder
        image: fluent/fluent-bit:latest
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
        volumeMounts:
        - name: logs
          mountPath: /var/log/govpn
          readOnly: true
        - name: fluentbit-config
          mountPath: /fluent-bit/etc
      volumes:
      - name: config
        configMap:
          name: govpn-config
      - name: certs
        secret:
          secretName: govpn-certs
          defaultMode: 0600
      - name: logs
        emptyDir: {}
      - name: tmp
        emptyDir: {}
      - name: fluentbit-config
        configMap:
          name: fluentbit-config
      nodeSelector:
        kubernetes.io/os: linux
      tolerations:
      - key: "node.kubernetes.io/not-ready"
        operator: "Exists"
        effect: "NoExecute"
        tolerationSeconds: 300
      - key: "node.kubernetes.io/unreachable"
        operator: "Exists"
        effect: "NoExecute"
        tolerationSeconds: 300
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app.kubernetes.io/name
                  operator: In
                  values:
                  - govpn
              topologyKey: kubernetes.io/hostname 